server.port=8084
spring.datasource.url=jdbc:mysql://localhost:3306/streamcast_database
spring.datasource.username=root
spring.datasource.password=ctssql2026
info.app.name=Partner-Service
info.app.description=This service manages partners, including their creation, retrieval, updating, and deletion.
info.app.version=1.0.0


resilience4j.circuitbreaker.instances.contractService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.contractService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.contractService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.contractService.waitDurationInOpenState=10000
resilience4j.circuitbreaker.instances.contractService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.contractService.max-attempts=3
resilience4j.circuitbreaker.instances.contractService.wait-duration=2s